AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  S3Bucket:
    Type: String
    Description: Name of the S3 Bucket to watch for events.
  EventTypes:
    Type: CommaDelimitedList
    Description: Comma delimited list of S3 event types that should trigger the invalidation.
  InvalidationPaths:
    Default: ''
    Type: String
    Description: (Optional) A comma delimited list of paths to invalidate.  If not set the key from the S3 event will be used.
  DistributionId:
    Type: String
    Description: The CloudFront distribution id to create the invalidation on.

Resources:
  EventWriter:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      CodeUri: ./dist
      Handler: S3EventHandler.handler
      Tracing: Active
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          DISTRIBUTION_ID: !Ref DistributionId
          INVALIDATION_PATHS: !Ref InvalidationPaths
      Events:
        S3Changes:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: !Split [',',!Ref EventTypes]
      Policies:
          - CloudFrontFullAccess